nameOverride: ''
fullnameOverride: ''
web:
  replicaCount: 1
  image:
    repository: tech3.azurecr.io/web
    tag: 1.0
    pullPolicy:
api:
  replicaCount: 1
  image:
    repository: tech3.azurecr.io/api
    tag: 1.0
    pullPolicy:
