apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  labels:
    app: app-api
    project: app
    part: api
    version: {{ .Values.api.image.tag }}
spec:
  selector:
    matchLabels:
      app: app-api
  replicas: {{ .Values.api.replicaCount | default 1 }}
  template:
    metadata:
      labels:
        app: app-api
        project: app
        version: {{ .Values.api.image.tag }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                - app
              - key: part
                operator: In
                values:
                - api
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy | default "IfNotPresent" }}
          resources:
            requests:
              memory: '256Mi'
              cpu: '125m'
            limits:
              memory: '512Mi'
              cpu: '1000m'
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          readinessProbe:
            httpGet:
              path: /health
              scheme: HTTP
              port: http
            initialDelaySeconds: 10
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              scheme: HTTP
              port: http
            initialDelaySeconds: 10
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
