apiVersion: v1
kind: Service
metadata:
  name: app-api
  labels:
    name: app-api
    part: api
    project: app
    version: {{ .Values.api.image.tag }}
spec:
  selector:
    app: app-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    # - name: https
    #   port: 443
    #   targetPort: https
    #   protocol: TCP
