apiVersion: v1
kind: Service
metadata:
  name: app-web
  labels:
    name: app-web
    part: web
    project: app
    version: {{ .Values.web.image.tag }}
    prometheus-ignore: "true"
spec:
  selector:
    app: app-web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    # - name: https
    #   port: 443
    #   targetPort: https
    #   protocol: TCP
