version: '3.8'

services:
  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8081:80"
  web:
    image: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
